# Generated by Django 4.0.4 on 2022-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('US', 'User')], default='US', max_length=2),
        ),
    ]
