# Generated by Django 4.0.4 on 2022-04-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['-height']},
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('height', 'hash')},
        ),
    ]
