# Generated by Django 4.0.4 on 2022-04-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_alter_block_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['height']},
        ),
    ]
