# Generated by Django 4.0.4 on 2022-04-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['datetime']},
        ),
    ]
